### ISSUE TITLE
Content Items with ListPart always returns empty

### ISSUE THREAD

**Issue by abbasl7** [ThisNetWorks/ThisNetWorks.OrchardCore.OpenApi#26]
Whenever we query for an item by Id (/api/content/{contentItemId}, all the parts are retrieved fine, but ListPart section is not populated.
I came across ListQueryHelpers in OrchardCore [link] (https://github.com/OrchardCMS/OrchardCore/pull/4865)
but not sure how to deal with that in the API world.

**Comment by deanmarcussen** [comment]
The ListPart is an empty marker class so it would always return empty.

to get the items of a list you would need to write an api controller to return them - we don’t expose a rest api for it currently. You could use the IContainerService to make the query.

or make a sql query and call that from the query rest endpoint.

alternatively make the query with graphql as it already supports that.
