### ISSUE TITLE
Always in "initializing" status when setup tenant with openapi recipe 

### ISSUE THREAD

**Issue by dev-hyang** [ThisNetWorks/ThisNetWorks.OrchardCore.OpenApi#27]
Hi, 
I am new here and playing around this openapi sample. But Always in "initializing" status when setup tenant with openapi recipe 
![image](https://user-images.githubusercontent.com/43012602/150871857-1350fd70-787c-437a-9799-f1653b4623df.png)

Or enable the OpenApi Module feature will cause the exist tenant into **dead** state no response.
Appreciate any advice. Thanks

**Comment by deanmarcussen** [comment]
Can you have a look at the logs?

**Comment by dev-hyang** [comment]
Unlucky, there was no log generated for the action. 
![image](https://user-images.githubusercontent.com/43012602/151002296-b2451174-f8fb-4cdb-9b1a-eeffbf760978.png)
But I found that the yessql.db-journal file was flashing. Could it be the yessql initializing/data loading failure?

**Comment by Skrypt** [comment]
Yes, more likely the database did not close a transaction properly.

**Comment by deanmarcussen** [comment]
@Skrypt  found the issue
